name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: make deps
    - name: build
      run: make release
    - name: download test data
      run: make download_test_data
    - name: run tests
      run: make tests
